
DROP SCHEMA IF EXISTS public CASCADE;

CREATE SCHEMA public;

CREATE TABLE users(
   id             INTEGER PRIMARY KEY, --generated by auth server
   email          VARCHAR(100),
   username       VARCHAR(100) UNIQUE     NOT NULL,
   disabled       BOOLEAN DEFAULT FALSE,
   created_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

CREATE SEQUENCE recipe_slug START 1;

CREATE TABLE slugs(
   slug           VARCHAR(100) PRIMARY KEY,
   created_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
   deleted_at     TIMESTAMPTZ    ,
   deleted        BOOLEAN NOT NULL DEFAULT FALSE
);



CREATE TABLE recipes(
   id             INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   title           VARCHAR(100)                NOT NULL,
   slug           VARCHAR(100)          NOT NULL,
   description    VARCHAR(500)               ,
   ingredients    VARCHAR(500)                ,
   recipe         VARCHAR(3000)               NOT NULL,
   author_id        INTEGER                NOT NULL,
   created_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
   deleted_at     TIMESTAMPTZ    ,
   deleted        BOOLEAN NOT NULL DEFAULT FALSE, 
   CONSTRAINT fk_recipes_author
      FOREIGN KEY(author_id) 
      REFERENCES users(id),
   CONSTRAINT fk_recipes_slug
      FOREIGN KEY(slug) 
      REFERENCES slugs(slug),
   UNIQUE (slug,deleted)
);

CREATE TABLE recipe_favorites(
   id             BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   recipe_slug    VARCHAR(100)     NOT NULL,
   user_id         INTEGER     NOT NULL,
   created_at     TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
   CONSTRAINT fk_recipe_favorites_recipe_slug
      FOREIGN KEY(recipe_slug) 
      REFERENCES slugs(slug),
   CONSTRAINT fk_recipe_favorites_user_id
      FOREIGN KEY(user_id) 
      REFERENCES users(id),
   CONSTRAINT unique_user_recipe_favorite
      UNIQUE (user_id, recipe_slug)
);

CREATE TABLE news(
   id             INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   type           VARCHAR(100)                NOT NULL,
   text           VARCHAR(500)                NOT NULL,
   title          VARCHAR(100)                NOT NULL,
   author_id      INTEGER                    NOT NULL,
   created_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
   recipe_slug    VARCHAR(100),
   CONSTRAINT fk_news_recipe_slug
      FOREIGN KEY(recipe_slug) 
      REFERENCES slugs(slug),
   CONSTRAINT fk_news_author_id
      FOREIGN KEY(author_id) 
      REFERENCES users(id)
);
